package pl.bratosz.seniorcarebackend.shared.error

//PERSISTANCE
val OBJECT_NOT_FOUND = "OBJECT_NOT_FOUND"
val RETRIEVAL_ERROR = "RETRIEVAL_ERROR"
val INSERTION_ERROR = "INSERTION_ERROR"

//VALIDATION
val EMPTY_UPDATE = "EMPTY_UPDATE"
val INCORRECT_INPUT = "INCORRECT_INPUT"
val JSON_MISSING_FIELD = "JSON_MISSING_FIELD"
val JSON_PARSING_ERROR = "JSON_PARSING_ERROR"
val JSON_BAD_REQUEST = "JSON_BAD_REQUEST"
